import { TextEdit } from "std-widgets.slint";
import { AppTheme } from "../theme.slint";

export component GjViewer inherits Rectangle {
    in property <string> terminal-text;
    in-out property <int> selected-line;
    in-out property <string> selected-context;

    border-width: 0px;
    background: AppTheme.bg;

    TextEdit {
        x: 0px;
        y: 0px;
        width: parent.width;
        height: parent.height;
        text: root.terminal-text;
        read-only: true;
        wrap: no-wrap;
        font-size: 13px;
        viewport-y: min(0px, self.visible-height - self.viewport-height);
    }
}
